name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      VITE_ADMIN_LINK_TO: ${{ secrets.VITE_ADMIN_LINK_TO }}
      VITE_APP_URL: ${{ secrets.VITE_APP_URL }}
      VITE_API_PUBLIC_URL: ${{ secrets.VITE_API_PUBLIC_URL }}
      VITE_API_URL: ${{ secrets.VITE_API_URL }}
      VITE_API_TOURS_PER_PAGE: ${{ secrets.VITE_API_TOURS_PER_PAGE }}
      VITE_STRIPE_PUBLIC_KEY: ${{ secrets.VITE_STRIPE_PUBLIC_KEY }}
      VITE_MAPBOX_API_KEY: ${{ secrets.VITE_MAPBOX_API_KEY }}
      VITE_CLOUDINARY_CLOUD_NAME: ${{ secrets.VITE_CLOUDINARY_CLOUD_NAME }}
      VITE_HERO_BG_IMG_URL: ${{ secrets.VITE_HERO_BG_IMG_URL }}
      VITE_LOGIN_BG_IMG_01_URL: ${{ secrets.VITE_LOGIN_BG_IMG_01_URL }}
      VITE_LOGIN_BG_IMG_02_URL: ${{ secrets.VITE_LOGIN_BG_IMG_02_URL }}
      VITE_LOGIN_BG_IMG_03_URL: ${{ secrets.VITE_LOGIN_BG_IMG_03_URL }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

   
    # Runs tests in parallel with matrix strategy https://docs.cypress.io/guides/guides/parallelization
    # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
    # Also see warning here https://github.com/cypress-io/github-action#parallel
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        containers: [1, 2] # Uses 2 parallel instances
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        # Uses the official Cypress GitHub action https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v6
        with:
          # Starts web server for E2E tests - replace with your own server invocation
          # https://docs.cypress.io/guides/continuous-integration/introduction#Boot-your-server
          build: npm run build
          start: npx vite --host
          wait-on: ${{ env.VITE_APP_URL }}
          # Records to Cypress Cloud 
          # https://docs.cypress.io/guides/cloud/projects#Set-up-a-project-to-record
          record: true
          parallel: true # Runs test in parallel using settings above

